### ISSUE TITLE
Allow 4MB ROMs

### ISSUE THREAD

**Issue by runer112** [calc84maniac/tiboyce#10]
Currently, both the rom converter and the TI-Boy launcher throw an error in response to a 4MB (256-page) ROM. Unless there's a technical limitation in the core emulator that would make support of a 256-page ROM hard or impossible, these limits should be lifted.

**Comment by mateoconlechuga** [comment]
I just want to say that I was able to build the rom generator on linux without any issues. What fun!

**Comment by adriweb** [comment]
Yes, it works fine on macOS as well :P

**Comment by mateoconlechuga** [comment]
But reddit is down so there's that

**Comment by calc84maniac** [comment]
Closed by #16.
