### ISSUE TITLE
Error: Need 5187 more bytes free RAM

### ISSUE THREAD

**Issue by Keryloss** [calc84maniac/tiboyce#106]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:5.4.0.0034
**TI-Boy CE version:Vo 1.3
**Describe your issue:**  
When I want to start an emulation, Ti boy say Error: Need 5187 more bytes free RAM

**Comment by Eeems** [comment]
The solution to this will be to free 5187 bytes of RAM. You can accomplish this by deleting variables/programs that are stored in RAM. If you have removed all of your variables/programs that are stored in RAM you may also need to remove archived programs as there is some RAM used to keep the list of programs stored.

**Comment by scratchermatch** [comment]
I had this issue, I have no idea how I fixed it but I did. Try archiving everything in your memory menu, and deleting other things you don't need on it. Sometimes taking the battery out and putting it back in can fix the issue. The problem is not always not having the required RAM for some reason.

**Comment by ultigiraffe** [comment]
Taking out the battery and putting it back in works 100% of the time for me. I got this error a lot for some reason and whenever I would delete any RAM/archieve (free storage) or add any it would both add to the RAM count so it is quite clear that this error message isn't accurate to what's really going on. Really weird stuff. I hope they fix this one. The battery trick should work more often than not.

**Comment by adriweb** [comment]
In order to fully reset the RAM (make sure to backup your stuff first or put them in Archive memory), instead of taking out the battery, you can simply press and hold the reset button on the back for around 3s.
