### ISSUE TITLE
Pokemon Red Game Clitch

### ISSUE THREAD

**Issue by Hunterwolffe** [calc84maniac/tiboyce#109]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.1.3.0058 (see in `2nd`+`mem` ->`About`)
**TI-Boy CE version:** TI-84 (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  
I was playing Pokemon Red when my character suddenly vanished along with all other characters on the screen. The game froze on the background. The only thing I can do is pull up the menu.

What are the steps to reproduce this issue?
-------------------------------------------
1. … Go to Lavender Town
2. … Go to Pokemon Volunteer House
3. … Talk to girl on right side of house

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…
![IMG_2547](https://user-images.githubusercontent.com/66433943/83786970-f31eeb00-a647-11ea-8ec6-27fabeedb699.jpeg)

**Comment by calc84maniac** [comment]
Couldn't reproduce this in v0.2.0, feel free to reopen if the bug still exists in this version.
