### ISSUE TITLE
Error: Missing AppVar (romname)R00

### ISSUE THREAD

**Issue by FlareTheTaco** [calc84maniac/tiboyce#111]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.4.0
**TI-Boy CE version:** v0.1.3
**Describe your issue:**  
I loaded up the menu and everything was fine, but I tried to load Pokemon Blue it gave me an error saying "Error: Missing AppVar PKBLUR00. PKBLU is what I named it btw. I installed everything as it should be, so I'm not sure what the issue is here.

What are the steps to reproduce this issue?
-------------------------------------------
1. idk load up the game?
2.
3. 

Any logs, error output, screenshot, other comments...?
------------------------------------------------------

![image](https://user-images.githubusercontent.com/68350532/87588804-4312b800-c6b2-11ea-8492-d22c2f2971c5.jpeg)

**Comment by jacobly0** [comment]
Did you send `PKBLUR00.8xv` and all of the other files that the rom converter generated to your calculator?
