### ISSUE TITLE
Pokemon Savefiles

### ISSUE THREAD

**Issue by NickTacke** [calc84maniac/tiboyce#116]
Is there any way I can get the pokemon save files from my calculator and edit them?

Cause then I could pretty much trade with my friends by removing the stuff I'm trading away and adding the stuff I'm getting from the trade.

If there's not is there any possibility you could add this?

**Comment by Eeems** [comment]
Savefiles are just appvars (https://github.com/calc84maniac/tiboyce#converting-save-files) so yes you can copy them back to your computer. And it looks like the converter allows you to convert from an appvar back to a pc emulator save file format: https://github.com/calc84maniac/tiboyce/blob/master/tiboyce-convertsav/convertsav.c#L451

**Comment by NickTacke** [comment]
Thanks, I’ve managed to retrieve the save file from the calculator. Then converted it to a .sav and edited it with PkHex, converted it back to a .8xv and sent it back to my calculator. And it seems like it worked perfectly.
