### ISSUE TITLE
Compatibility for version 5.5 and up?

### ISSUE THREAD

**Issue by FerdinandoPH** [calc84maniac/tiboyce#117]
Is this ever going to happen?

**Comment by FerdinandoPH** [comment]
I really love this project, but I cannot use it because of this

**Comment by Eeems** [comment]
Well technically 5.5 and up don't support ASM. Have you tried using [arTIfiCE](https://yvantt.github.io/arTIfiCE/) to run it?

**Comment by FerdinandoPH** [comment]
I had no idea that existed. Thanks!
