### ISSUE TITLE
Invalid Gameboy Opcode

### ISSUE THREAD

**Issue by BioHazard1282** [calc84maniac/tiboyce#121]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.4.0.0034
**TI-Boy CE version:** Latest, 0.13a
**Describe your issue:**  
Every game has the same error: "Ran an invalid Game Boy opcode at 01C20E"

What are the steps to reproduce this issue?
-------------------------------------------
1. Run any Gameboy Game on OS 5.4.0.0034

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
Ran an invalid Game Boy opcode at 01C20E

**Comment by Eeems** [comment]
For the TI-Boy CE version I think you mean v0.1.3 alpha. That release was meant for hardware revisions model M, if you weren't experiencing that, I'd suggest downgrading to v0.1.2 alpha.

**Comment by calc84maniac** [comment]
I wouldn't really suggest downgrading, especially if there's a chance you have newer hardware.

Are there any specific examples of games this is happening to?

**Comment by BioHazard1282** [comment]
Super Mario Land 2, Alien 3, Donkey Kong 2, Dr. Mario
This is on a real calculator, not CEmu

**Comment by BioHazard1282** [comment]
So it could be a calculator problem or game problem then

**Comment by calc84maniac** [comment]
Closing unless this can be reproduced in the newest version.
