### ISSUE TITLE
pokemon gold turbo mode

### ISSUE THREAD

**Issue by Manupokemonhunter** [calc84maniac/tiboyce#123]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … (see in `2nd`+`mem` ->`About`)
**TI-Boy CE version:** … (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. 5.3.1.0058
2. Alpha v0.1.3
3. when iam playing pokemon gold and i push the turbo button instead of speeding the game up it even slows it down. if I push this button again It doesn't even come back to the normal state. and stays in this slow turbo mode.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by calc84maniac** [comment]
In the currently released version some games like Pokemon Gold/Silver run pretty slowly, but I've got some major improvements for that already lined up for the next release (or if you're really adventurous you can build the dev branch).

It's likely that it was already slow before you activated turbo, but by default the speed display isn't shown unless it's activated (this can be changed in the settings).
