### ISSUE TITLE
color correction

### ISSUE THREAD

**Issue by ILikeTrees05** [calc84maniac/tiboyce#124]
the colors are not similar to an actual Gameboy and I would prefer if it was color corrected so you could get closer to the real experience

I would want another color option in the graphics menu

making this the default would work well too

this would switch to GBC color correction when playing a GBC game

**Comment by thegamingnobody** [comment]
The emulator doesn't support game boy color yet, and the palettes available are those from the super game boy on the snes. That's why they aren't the real palettes, it's still original game boy

**Comment by MobambaCare** [comment]
You can play GBC games on it, but only if you change the file name from .gbc to .gb.

**Comment by calc84maniac** [comment]
Color correction has been added to v0.2.0, though it still only applies to colorization palettes since GBC is not yet supported.
