### ISSUE TITLE
Invalid Compression Type 50 when converting SAV.8vx to .sav or .srm

### ISSUE THREAD

**Issue by JacquesOLantern** [calc84maniac/tiboyce#127]
I just want to start out by saying that I'm not that good with computers, so bear with me here. I'm trying to backup my save from Pokemon Silver to my computer just in case my TI-84 Plus CE gets wiped or something, but every time I try converting my SAV.8xv file into a .sav or .srm using the online convertor on github, calc84maniac.github.io says," Invalid compression type 50" no matter what I name it. Does anyone know a fix to this, or am I just typing the file name in wrong?

**Comment by JacquesOLantern** [comment]
Okay now that I've named my save file SAV.sav (though its still an 8.xv), I got past Compression Type 50, but now it says that AppVar has to end in SAV, which it does since I named it SAV.sav. I'm absolutely doing something wrong here, so could anyone help?

**Comment by Eeems** [comment]
Sounds like you are hitting a new error insted of getting past the old one. Try renaming it to something like `ASAV.8xv` like in the instructions: https://github.com/calc84maniac/tiboyce#converting-save-files

Likely you'll get back to the `Invalid Compression Type 50` error which leads me to believe that either the format used for the appvar has changed but the conversion tools weren't updated, the file is corrupted, or there is a bug with the tool.

From what this code is telling me, the value it should be finding is either `0` or `1`. https://github.com/calc84maniac/tiboyce/blob/master/tiboyce-convertsav/convertsav.c#L231-L260

**Comment by calc84maniac** [comment]
Generally if you've gotten your save file off the calculator, you shouldn't have to rename it. It'll already have a name ending in `SAV.8xv` (if it doesn't, that means you probably transferred over the wrong file). The invalid compression type message does make me think it's either the wrong file or got corrupted somehow, but if the save still works on the calculator I wouldn't think it got corrupted.

**Comment by JacquesOLantern** [comment]
Okay, I was importing EzDCSAV instead of the right file and its working now. Thank you!
