### ISSUE TITLE
question - how do you use the dev branch? 

### ISSUE THREAD

**Issue by StandingPadAnimations** [calc84maniac/tiboyce#131]
So I was interested in using the dev version, but I'm not sure how I install it and how to use it with existing ROMs.

**Comment by calc84maniac** [comment]
First download the dev branch, you can either clone the repository with Git or download the code as a ZIP from [https://github.com/calc84maniac/tiboyce/tree/dev](https://github.com/calc84maniac/tiboyce/tree/dev)

The instructions to build the emulator from source are in the readme, it will output .8xp and .8xv files that you can send to the calculator. It should still be compatible with the existing ROM format, so no need to build the converters yourself or anything.

I apologize for not making a release in such a long time, I just keep finding more and more things I want to improve, but I end up taking my sweet time actually working on them...

**Comment by StandingPadAnimations** [comment]
Thanks! I think taking your time is a good idea since it makes the quality even better
