### ISSUE TITLE
Error: Missing AppVar MmmmR00

### ISSUE THREAD

**Issue by MoIsBadAtCoding** [calc84maniac/tiboyce#132]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … 5.3.0.0037
**TI-Boy CE version:** … v0.1.3
**Describe your issue:**  
I loaded my ROM onto the calculator only for it to tell me the App is missing

What are the steps to reproduce this issue?
-------------------------------------------
1. Attempting to run the game
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![Photo on 8-22-21 at 9 47 PM #2](https://user-images.githubusercontent.com/89368810/130383163-c4335457-0c61-495e-a226-02185d2afc4c.jpg)

**Comment by Eeems** [comment]
Have you transferred the MmmmR00 appvar to your device?

**Comment by MoIsBadAtCoding** [comment]
Actually I was able to figure it out. I sent a bundle of my ROM. Thanks.
