### ISSUE TITLE
Can't launch emulator

### ISSUE THREAD

**Issue by stereo18** [calc84maniac/tiboyce#134]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.6.1.0012
**TI-Boy CE version:** Alpha 0.1.13
**Describe your issue:**  
Can't launch the emulator

What are the steps to reproduce this issue?
-------------------------------------------
1. Just launch the emulator with and without game

![Capturer 1](https://user-images.githubusercontent.com/40271484/131219838-3bf1d543-4d93-4c6b-a357-132a3299e659.png)

**Comment by adriweb** [comment]
Expected for your OS version, follow the instructions here: https://yvantt.github.io/arTIfiCE/
