### ISSUE TITLE
How do i play pokemon red as it says i need 5150 more bytes of ram? I deleted all the other games than 2 i wanted, Please help!!!

### ISSUE THREAD

**Issue by DogKeeperAnthony** [calc84maniac/tiboyce#135]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … (see in `2nd`+`mem` ->`About`)
**TI-Boy CE version:** … (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by DogKeeperAnthony** [comment]
I open the game through apps btw if that changes anything.

**Comment by jacobly0** [comment]
You can archive variables in the `2nd` `+` `2` memory menu my pressing `enter` which means that they won't take up space in ram.

**Comment by DogKeeperAnthony** [comment]
> You can archive variables in the `2nd` `+` `2` memory menu my pressing `enter` which means that they won't take up space in ram.

it still says it needs 6k ram

**Comment by DogKeeperAnthony** [comment]
@calc84maniac

**Comment by DogKeeperAnthony** [comment]
my friend fixed it
