### ISSUE TITLE
Does this emulator run on bare metal on ti calculators?

### ISSUE THREAD

**Issue by eltomas2003** [calc84maniac/tiboyce#144]

**Comment by calc84maniac** [comment]
By bare metal, do you mean without the presence of an operating system? It does currently rely on the OS for basic hardware initialization and file operations, but the emulation core doesn't rely on the OS. It would be possible to fork the emulator and replace all references to OS calls, though it would be a bit of work.

**Comment by eltomas2003** [comment]
so the os is like the bios of the console, but the actual emulation is bare metal, when your playing a gb game via emulator, it is part of the software and not part of the os, that's why you can't dim the lights or turn off the Ti-84 calc while playing

**Comment by calc84maniac** [comment]
Right, there's no OS code running during emulation. I could potentially add some backlight controls to the emulator (and I probably should), not sure about turning off the calculator but the save state feature is good enough for exiting the emulator to turn it off.

**Comment by eltomas2003** [comment]
you could add some code that allows you to turn off the calc by pressing the on button

**Comment by eltomas2003** [comment]
perhaps auto-off after the calculator is idle for a few minutes?

**Comment by eltomas2003** [comment]
Why doesn't the emulator interact in tandem with the OS like in PSP games? 
["games developed for this console are not written for bare-metal: instead of relying on memory address and ports, they would have to call modules to perform operations on the hardware."](https://www.copetti.org/writings/consoles/playstation-portable/)

**Comment by Eeems** [comment]
> Why doesn't the emulator interact in tandem with the OS like in PSP games? 
> ["games developed for this console are not written for bare-metal: instead of relying on memory address and ports, they would have to call modules to perform operations on the hardware."](https://www.copetti.org/writings/consoles/playstation-portable/)

So it can be fast. TI-OS isn't known for being that fast. TI-Boy also needs access to large amounts of ram, which TI-OS would clobber. I believe that TI-Boy makes interesting use of all the registers, and TI-OS would clobber them as well.
