### ISSUE TITLE
How do I delete a game that I download onto my calculator????

### ISSUE THREAD

**Issue by achow0** [calc84maniac/tiboyce#147]
I just need to know how to delete (not archive) a game I download onto my calculator and any related save files, etc, without clearing anything else on my calculator. I have TI-84 Plus CE if that matters. Thanks for the help.

**Comment by adriweb** [comment]
Use the memory management menu (2nd then Plus), go to the "All" submenu, then press Del on the entries related to the things you want to delete.

**Comment by achow0** [comment]
> Use the memory management menu (2nd then Plus), go to the "All" submenu, then press Del on the entries related to the things you want to delete.

I have Pokemon Red on my TI-84 Plus CE, what are the things I should delete? I don't want to accidentally delete something that is important.
