### ISSUE TITLE
Black Screen When Booting Up Pokemon Red

### ISSUE THREAD

**Issue by ThomasDaTraim** [calc84maniac/tiboyce#148]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:**  (5.6.1)
**TI-Boy CE version:**  (alpha v0.1.1)
**Describe your issue:**  (My issue is that when I went to boot up Pokémon Red using Cesium I go into the Ti- Boy CE launcher and press enter on Pokémon Red and after that I get a black screen and have to press the reset button to get out of the black screen.)  

What are the steps to reproduce this issue?
-------------------------------------------
1. Click apps and go into Cesium
2. Click TIBOYCE
3.  Once In TIBOYCE click whatever you called the rom and it gives

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…![GB Caculayor](https://user-images.githubusercontent.com/92267534/136705893-6bbacbca-71ef-4ec2-9a65-b19ef354825b.PNG)
Files in the calculator 
![Capture1-1633885395386](https://user-images.githubusercontent.com/92267534/136705959-86765f6c-3935-4abb-a1a6-157d574954bc.png)
My version and the Pokémon Red

**Comment by adriweb** [comment]
You have a very old version, please try with the latest release: https://github.com/calc84maniac/tiboyce/releases/latest
(Note that it may get an update in the coming weeks/months, so check for updates from time to time)
