### ISSUE TITLE
Garbage collect after turning off Pokémon Red

### ISSUE THREAD

**Issue by Fling0** [calc84maniac/tiboyce#151]
I have been playing pokemon red for some time on my Ti-84 + CE calculator and suddenly, when i turn off pokemon red, the garbage collect message appeared. I selected "no", then a warning came up "Warning: Failed to archive AppVar PokeSTA". How do i remove the garbage collect message? Is it safe to do the garbage collect, will the files disappear?
![20211117_181121](https://user-images.githubusercontent.com/94517535/142154018-24b4395f-850d-4d8e-9233-061cbe2d3b20.jpg)

![20211117_181046](https://user-images.githubusercontent.com/94517535/142153873-4dfc68fb-8665-4cbc-b0c3-fd19ff0f7613.jpg)

**Comment by jacobly0** [comment]
Garbage Collect only erases previously deleted variables and rearranges the currently existing ones to make room for archiving more variables.  You will need to run it and wait some time for it to complete before you can continue using your archive.

**Comment by Fling0** [comment]
> Garbage Collect only erases previously deleted variables and rearranges the currently existing ones to make room for archiving more variables. You will need to run it and wait some time for it to complete before you can continue using your archive.

thank you

**Comment by Fling0** [comment]
> Garbage Collect only erases previously deleted variables and rearranges the currently existing ones to make room for archiving more variables. You will need to run it and wait some time for it to complete before you can continue using your archive.

Okay, the garbage collect was very quick, it just finished. Now i dont have the problem anymore
