### ISSUE TITLE
Donkey Kong file select screen is broken

### ISSUE THREAD

**Issue by rileydavies** [calc84maniac/tiboyce#154]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.4
**TI-Boy CE version:** Alpha v0.2.0
**Describe your issue:**  
the file select screen is broken in donkey kong. starts with file 3 selected, moving the character around doesn't stop at or highlight different save files.

What are the steps to reproduce this issue?
-------------------------------------------
1. run donkey kong
2. press start to get to file select screen
3. attempt to load files correctly. I believe the only one you can load currently is file 3, both 1 and 2 are inaccessible.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
This worked correctly in Alpha v0.1.3, so its a bug in the new update which is to be expected.

**Comment by calc84maniac** [comment]
This was an issue that I somehow managed to cause two days before release... I've fixed it and updated the release package, so please redownload v0.2.0 to fix the issue.

**Comment by rileydavies** [comment]
> This was an issue that I somehow managed to cause two days before release... I've fixed it and updated the release package, so please redownload v0.2.0 to fix the issue.

hmm. I redownloaded it and yes it seems to work except for when I try to use my previous save file then the glitch is still there. I tried converting it to other formats and back, tried unarchiving and re archiving and stuff but seems to be the actual save has wrote the glitched state to memory. Even attempting to save extra progress to overwrite stuff doesn't seem to work. Any way to fix my save file or is it permanently screwed up?

**Comment by calc84maniac** [comment]
Oh yeah, it's definitely possible the save got corrupted from this glitch... I'm sorry about that. If you have an old manual save state then loading it should restore the associated save data as well, but other than that you'd need a copy of the save file from before running it on the bad version.

**Comment by rileydavies** [comment]
It's alright. I'm just glad I could notify you of this issue early enough to hopefully prevent most from loosing their data now :)
