### ISSUE TITLE
Ti 84 plus ce crashes and says validating OS when I try to run any rom

### ISSUE THREAD

**Issue by FreshSamurai** [calc84maniac/tiboyce#156]
So, whenever i try to run a game in TIBOYCE my calculator says Validating OS calculator will restart when complete. And then after that i cant even open the TIBOYCE app anymore throught cesium. Im not sure if I should delete TIBOYCE and try again or what.

**Comment by adriweb** [comment]
Can you provide more information about your calculator? Which OS version is it running, which [hardware revision / datecode](https://i.imgur.com/uhISPgh.png) the calculator has, and anything else you may deem useful to help.

**Comment by FreshSamurai** [comment]
5.6, and its Python Edition

**Comment by calc84maniac** [comment]
Do you get any particular error messages or other odd behavior when running through Cesium? It may be helpful to transfer the TIBOYCE and TIBoyDat files to your PC, and zip and upload them here so I can check and see if they got corrupted somehow.

**Comment by FreshSamurai** [comment]
No error messages thru cesium

**Comment by FreshSamurai** [comment]
[tiboyce.zip](https://github.com/calc84maniac/tiboyce/files/7681100/tiboyce.zip)

**Comment by FreshSamurai** [comment]
hey also do u think u could add me on discord? im on CE programming

**Comment by calc84maniac** [comment]
I meant sending the files back to the PC from the calculator, but it also appears that what you uploaded was the v0.1.3 release. Could you try the new v0.2.0 release and see if that works better?

**Comment by FreshSamurai** [comment]
ok i will try that

**Comment by FreshSamurai** [comment]
It worked. Thanks
