### ISSUE TITLE
TI - 84 CE python not working

### ISSUE THREAD

**Issue by Sameer152010** [calc84maniac/tiboyce#160]
After doing all the steps correctly I always end up with the error: INVALID when initializing Tiboy program. If you know how to fix please help. I am not sure if it is specific to python edition but it wont work at all.

**Comment by calc84maniac** [comment]
I believe the Python Edition has a new enough OS version that you have to use the arTIfiCE jailbreak, which should be linked in the readme. Did you do that?

**Comment by ego-lay-atman-bay** [comment]
I have the ti-84 plus ce python, and yes, I had to install arTifICE to get tiboy to work.
