### ISSUE TITLE
Difficulties with the skin converter python file

### ISSUE THREAD

**Issue by BrickWildcat** [calc84maniac/tiboyce#164]
I've edited the [gb_skin.png](https://github.com/calc84maniac/tiboyce/blob/master/gb_skin.png) file that comes with the source code to look like a Game Boy Pocket, and I now want to send that file to my calculator to use as my GB skin. I've tried to run the [conv_skin.py](https://github.com/calc84maniac/tiboyce/blob/master/conv_skin.py) file in a folder with [my gb_skin.png image](https://cdn.discordapp.com/attachments/960898056809771018/972216877893951548/gb_skin.png), like so:
`~/Downloads/tiboyce-0.2.1 $ python conv_skin.py`
but it returns this error:
`Traceback (most recent call last):
  File "/home/[realname]/Downloads/tiboyce-0.2.1/conv_skin.py", line 15, in <module>
    for (r, g, b) in zip(pal[0:48:3], pal[1:48:3], pal[2:48:3]):
TypeError: 'NoneType' object is not subscriptable`
I'm not sure what causes this issue, but I at least am 100% that I have the lzf module installed on my system. The struct module is a bit less clear - running `python -m pip install struct` doesn't work but `python -m pip install python_struct` does, so I may or may not have that module, I'm not quite sure.
Other than that, maybe this is a color palette issue? I'm really not sure what to make of the error message. Some help would be appreciated.
I'm running Manjaro Linux (KDE) on the 5.17.1-3 kernel, if that matters.

**Comment by calc84maniac** [comment]
The image file has to be saved with a 16-color palette (e.g. use Indexed color mode in GIMP), the skin converter doesn't determine the palette itself. I assume that's your problem anyway, I can't inspect the PNG file right now.

**Comment by BrickWildcat** [comment]
After [changing the image](https://cdn.discordapp.com/attachments/960898056809771018/973029528542806016/gb_skin.png) to a 16-color palette using GIMP's index mode, running the script outputs an error message that, as far as I can tell, is just... false?
`Traceback (most recent call last):
  File "/home/[realname]/Downloads/tiboyce-0.2.1/conv_skin.py", line 32, in <module>
    data = palette + compress(bytes(data))
  File "/home/[realname]/Downloads/tiboyce-0.2.1/conv_skin.py", line 8, in compress
    return struct.pack('<H', len(data)) + lzf.compress(data)
AttributeError: module 'lzf' has no attribute 'compress'`

**Comment by calc84maniac** [comment]
It looks like there are two different LZF modules on PyPI. I think the one I probably used was python-lzf.

**Comment by BrickWildcat** [comment]
That was the issue, my png was successfully converted to assembly (yay!).
I hate to be _that guy_, but now what? [An online 8xv converter](https://github.com/keoni29/ti83f) didn't seem to do the trick, even after renaming the AppVar to include lowercase letters (in Cesium).

**Comment by calc84maniac** [comment]
For that I can refer you to the [Build Instructions](https://github.com/calc84maniac/tiboyce#build-instructions) in the readme.

Sorry this whole process isn't that user-friendly, it was really just an internal tool that's in the repo for completeness' sake.

**Comment by BrickWildcat** [comment]
To be honest, I'm glad it exists in the first place! :)
Thank you for your help on this issue, I love the emulator and it's fun to be able to personalize, even if it's a bit difficult.
