### ISSUE TITLE
Color issue with Pokémon gold and silver.

### ISSUE THREAD

**Issue by EndangeredBubs** [calc84maniac/tiboyce#165]
Hello, I own the Ti84 CE Plus Python and Pokémon Red, Blue, and Yellow all work perfectly fine but whenever I try Pokémon gold or silver its just a gray colors. I also have another question about the turbo mode to make things faster why does it go so quickly on red but in blue or yellow its slower?

**Comment by calc84maniac** [comment]
There isn't actual Game Boy Color support yet, so original Game Boy games (such as Red and Blue) run using predefined default palettes as if running on a GBC, but games like Gold and Silver are GBC-enhanced so they have no default palette. For now you can set a custom palette in the settings if you want, though it's not full colorization.

As for turbo speed, it's limited by the emulation performance, so more complex games won't run as fast (and some games won't speed up at all). You can improve the maximum turbo speed slightly at a trade-off for visual smoothness by increasing the maximum frameskip value.

**Comment by teddblue** [comment]
just wondering, how does the reverse palette know the colors in the game (it's reversing them) while the default doesn't?
