### ISSUE TITLE
cauculator emulator for ti-84 plus ce wont work for pokemon

### ISSUE THREAD

**Issue by xbgamer** [calc84maniac/tiboyce#167]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------There is an error that says invalid e
**TI-OS version:** ti-84 plus ce 
**TI-Boy CE version: most likely not the latest
 It is not letting me get to the rom file it should allow me to get to the rom and play it.

What are the steps to reproduce this issue?
-------------------------------------------
1.see what the problem is 
2. Fix it
3. Get it to work

Any logs, error output, screenshot, other comments...?
-----
![E76A0475-A69E-474E-B1F6-9BA7E87EFE46](https://user-images.githubusercontent.com/109440961/179380756-b2731e7b-120b-411f-9a9a-8e8b4b66117e.jpeg)
-------------------------------------------------
…

**Comment by xbgamer** [comment]
it says file invalided

**Comment by Eeems** [comment]
@xbgamer it looks like you left the template blank. Please fill out the issue template.

**Comment by xbgamer** [comment]
![D3BDA8E1-02E2-40BF-BE92-30A0BF2AA6E9](https://user-images.githubusercontent.com/109440961/179380239-09da137f-f4d5-4e19-adbb-b1c7568931c7.jpeg)

**Comment by Eeems** [comment]
@xbgamer again, you aren't filling out the template, please edit your first message and fill out the fields

**Comment by xbgamer** [comment]
I did

**Comment by adriweb** [comment]
No you haven't (OS version, TI Boy version, etc.).

Regardless, it seems your problem is not related to TI-Boy CE but the fact that you're trying to use ASM programs on an OS that's 5.5 or later. in which case, you need to jailbreak and use Cesium and/or AsmHook to launch asm programms. See [arTIfiCE](https://yvantt.github.io/arTIfiCE/) for more info,

**Comment by xbgamer** [comment]
Ok fixed it

**Comment by xbgamer** [comment]
thank you for the help it works fine now

**Comment by adriweb** [comment]
I'm not sure if you're being unhelpful/snarky/immature on purpose but you're not providing any valuable information.  "TI-OS version: ti-84 plus ce" and "TI-Boy CE version: most likely not the latest" is useless.
Closing as apparently you don't seem to want to help people help you, and I've already given you what's probably the resolution anyway.
