### ISSUE TITLE
Link Cable Multiplayer

### ISSUE THREAD

**Issue by Darkturtle999** [calc84maniac/tiboyce#173]
**Is your feature request related to a problem? Please describe.**
Pokémon Red cannot have a completed pokedex without trading

**Describe the solution you'd like**
I would like to connect 2 TI-84 CE calculators with a cable and play in multiplayer

**Describe alternatives you've considered**
I have tried save editing but I cannot find a way to convert a TI-boy CE save to a normal save I can save-edit

**Additional context**
I do not know how achievable this is so say something if its just 100% impossible

**Comment by calc84maniac** [comment]
I wouldn't say it's impossible, there's actually an issue open for it already: #30 

It would take a good bit of work however, and I'm prioritizing Game Boy Color support right now. I'm also waiting for the community USB libraries to mature a bit before I start working with them.

As for save editing, there is actually a save converter both in the release and on the website next to the ROM converter. The conversion works in both directions.

**Comment by Darkturtle999** [comment]
Oh thanks I didn't know it worked both ways
