### ISSUE TITLE
GBA support

### ISSUE THREAD

**Issue by LeeRyanSA** [calc84maniac/tiboyce#180]
Will you ever port the Game Boy Advanced? The Gameboy Color is now supported, and so why not go a step further? I'm merely asking due to there being no reason provided for "Never the Gameboy Advanced". Thanks!

**Comment by calc84maniac** [comment]
Basically, the Game Boy Advance is at least like 5 steps further. It's a 32-bit system (the calculator is 8-bit), the graphics are really complex (you'd be lucky to get that level of graphics even in a native calculator game), it has more RAM than the calculator (when including the necessary framebuffers for rendering), and most games wouldn't fit in the calculator's Archive storage in the first place.

So yeah, there are real reasons. I'm not one to back down from a challenge, but the Game Boy Color is actually a reasonable challenge.

**Comment by LeeRyanSA** [comment]
Ah, thank you. So, the Ti-84 itself isn't that advanced to support the GBA due to the varying bit systems and the sheer file sizes of the ROMs are a problem? I fully understand. Thanks!
