### ISSUE TITLE
Archive Error when I try to run TIBOYCE

### ISSUE THREAD

**Issue by pedrojogaco** [calc84maniac/tiboyce#182]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:*5.8.0* … (see in `2nd`+`mem` ->`About`)
**TI-Boy CE version:*v0.1.3* … (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
**Describe your issue:*When I try to run TIBOYCE in my calculator it gives me an error "ERROR:  INVALID"*  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …press "prgm"
2. …go to TIBOYCE and press enter
3. …press enter again to run the program

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…"ERROR:  INVALID" and then above it says "Attempted to use a variable or function where it is not valid."

**Comment by adriweb** [comment]
Moreover, make sur to download [the latest release](https://github.com/calc84maniac/tiboyce/releases/latest) (v0.3.0 at this time), as your version 0.1.3 is very old.

**Comment by pedrojogaco** [comment]
Thanks for the help
