### ISSUE TITLE
Game crash in Dragon Warriors Monsters 2: Cobi's Journey

### ISSUE THREAD

**Issue by Chenyi2008** [calc84maniac/tiboyce#183]

**Comment by Chenyi2008** [comment]
Dragon warrior monster2 crash on a particular screen

**Comment by Chenyi2008** [comment]
like it only crash when I walk to that part of the screen, it won't affect the game if i was walking some other places. but this made me can't play the game because its screen that creates the crash was contain a dungeon that is required to pass the section. please help, I replay the game 2 times and it always crash at that part. After the crash, it has a lot of color on the entire calculator screen and after I restart the calc, it said the file was not availiable.

**Comment by calc84maniac** [comment]
Which edition of the game are you playing? Can you provide some more information about exactly where in the game this happens, or provide a save file from slightly before that point?

Also, from your description I assume it's causing the entire emulator to crash, to the point you can't get to the menu?

**Comment by Chenyi2008** [comment]
i can get to the menu again but can't run the game, I don't have the save file but in the game, it was in a world called the sky key world in a dungeon on the botton, it is dragon warrior monster 2 cobi's journey. it is more than half way through the game

**Comment by Chenyi2008** [comment]
the game end up with lot of color block and the game just froze there, i need to click on to make it go back to the calculater calculating page
