### ISSUE TITLE
Is it possible to extract the save data from my game Ti-84.

### ISSUE THREAD

**Issue by naldo29** [calc84maniac/tiboyce#184]
Ive been playing pokemon yellow and im very close to finishing it but i recently ended school. I dont want to use this calculator anymore to finish this game, id like to play it on my steam deck, for that i need the save data of the game but i frankly dont know how to extract the data or if its even possible to do so. Is it possible? please let me know. thanks!

**Comment by naldo29** [comment]
nvm i figured it out

**Comment by Eeems** [comment]
Have you read the readme?
