### ISSUE TITLE
Gbc error

### ISSUE THREAD

**Issue by pieman100** [calc84maniac/tiboyce#186]
I put legend of Zelda oracle of ages for the GBC on my calculator but when I load it it says “ this game can only be played on GBC” regular game boy games work but not GBC games what’s wrong?

**Comment by adriweb** [comment]
Make sure to use the very latest version of TI-Boy CE?  See here https://github.com/calc84maniac/tiboyce/releases/latest

**Comment by pieman100** [comment]
Is there a way i can check the version on my calculator before I redo w load it

**Comment by adriweb** [comment]
It's displayed in the menu, but it doesn't matter since it's outdated
anyway, apparently. --
Thank you,
Adrien Bertrand
