### ISSUE TITLE
Converting saves on linux terminal

### ISSUE THREAD

**Issue by julenvitoria** [calc84maniac/tiboyce#190]
Hi!! First of all thanks for this work, it’s great!!! I want to convert my saves on linux terminal, is there any way to make it or I need to use windows? Thanks in advance! :)

**Comment by mateoconlechuga** [comment]
Here's a PR that describes how to do so: https://github.com/calc84maniac/tiboyce/pull/126/files

**Comment by julenvitoria** [comment]
Sorry for not replying but I've been very busy.  Thanks for the info, I was able to compile it a few days ago, apparently it works but I still have to try it with some srm.  Thank you very much for everything!!
