### ISSUE TITLE
For whatever reason I can't import TIBOYCE.8xv Ti-Connect just doesn't respond to it

### ISSUE THREAD

**Issue by Shyblook1234** [calc84maniac/tiboyce#191]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.3.1.0058
**TI-Boy CE version:** V0.3.0
**Describe your issue:**  I can't import TIBOYCE.8xp , Ti-Connect just doesn't respond to it 

What are the steps to reproduce this issue?

1. Open Ti connect
2. Select "Add content from computer to connected calculator"
3. Select file:TIBOYCE.8xp
4. Hit "Open" on the file menu
5. Then watch as nothing happens

Any logs, error output, screenshot, other comments...?
It doesn't show any type of error and normally it just doesn't show files that can't be sent, it just doesn't work

**Comment by Eeems** [comment]
You should probably fill out all the blanks in the issue template.

**Comment by Shyblook1234** [comment]
Ok, I hust did that, sorry

**Comment by Eeems** [comment]
Can you send other files to your calculator using TI-Connect without issue?

**Comment by Shyblook1234** [comment]
It seems like I can send anything except .8xp files that I didn't copy from the calculator (as in programs I made on the calculator are fine even though they're .8xp files) but other files work just fine

**Comment by adriweb** [comment]
Are you using the chrome version of ti connect ce? If so, it won't transfer asm programs yeah. You can try using https://ticalc.link for those.

**Comment by Shyblook1234** [comment]
That worked! thanks a million.
