### ISSUE TITLE
TIBoyCE Not Finding Roms

### ISSUE THREAD

**Issue by TheBetterTesla** [calc84maniac/tiboyce#199]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … 5.7.0.0021
**TI-Boy CE version:** … Alpha 0.3.0

After moving data from a USB drive TIBoyCE doesn't find the roms (which I have played before). 

What are the steps to reproduce this issue?
-------------------------------------------
1. Put a USB drive into the calculator using an adapter
2. Copy the roms on it to your calculator in Cesium (make sure they archive)
3. Open TIBoyCE

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
No

**Comment by calc84maniac** [comment]
Are you sure you copied all the ROM appvars? If the one containing _just_ the 5-letter prefix isn't present, the ROM won't be listed.

**Comment by TheBetterTesla** [comment]
Ah no I didn't. Thanks

**Comment by TheBetterTesla** [comment]
That was the problem.
