### ISSUE TITLE
Rearrange entries in emulator pause menu

### ISSUE THREAD

**Issue by runer112** [calc84maniac/tiboyce#2]
The fact that the savestate entries are stuck in the middle of the "options" entries is kind of silly. I'd suggest hoisting the savestate entries to the top and grouping the three "options" entries in the middle. You could also removing the spacing between them, like the group of three entries below.

If you also choose to implement #1 the "hard" way, highlighting the load savestate entry would have small short-term performance implications, so it should be made difficult to unintentionally highlight. I'd suggest making whatever entry comes after the savestate entries be the default highlighted entry, and if exiting the menu with the cursor on the load savestate entry, bump it back to the default highlighted entry.

**Comment by mateoconlechuga** [comment]
I am impressed by how little you had to change to fix this issue

**Comment by runer112** [comment]
Decided not to remove the spacing between the three now-contiguous options entries?

**Comment by calc84maniac** [comment]
It didn't feel right, and they're not really related aside from having "options" in the name.
