### ISSUE TITLE
Streetfighter 2 regularly crashes

### ISSUE THREAD

**Issue by foto1000** [calc84maniac/tiboyce#20]
It crashes a lot at the character selection screen, and when idling too long at the title screen, when the demo plays, and you try to get back to the game.
It always results in the same Error: Encountered an invalid opcode!

**Comment by mateoconlechuga** [comment]
Might be able to use this to track down the other ones; it seems a lot more repeatable :)

**Comment by calc84maniac** [comment]
This issue was caused by call stack optimization not taking swappable banks into account upon returning. Unfortunately, this seems to be unrelated to the other issues.

**Comment by calc84maniac** [comment]
It's not looking likely. There's a specific Game Boy code pattern that would have triggered this glitch, and I wasn't able to trigger the new check I added for the issue (which would have detected any such code pattern) while running Pokemon.
