### ISSUE TITLE
Cesium saying error:tiboydat missing

### ISSUE THREAD

**Issue by Calculatergamer** [calc84maniac/tiboyce#202]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version
I'm on the latest version of TI boy and it won't open on cesium
**TI-OS version:** … 5.8
**TI-Boy CE version:** … Alpha Version 0.3.0
**Describe your issue:**  
… tried to open it in cesium and it showed an error when trying to make sure it works for my friend

What are the steps to reproduce this issue?
-------------------------------------------
1. … try to open it in cesium
2. … that's it
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…
![image](https://github.com/calc84maniac/tiboyce/assets/150862630/d6fd6e58-2a53-429f-9006-c09ae5ab09fe)

**Comment by calc84maniac** [comment]
Did you send the TIBoyDat.8xv file?

**Comment by Calculatergamer** [comment]
I think I did I'll double check but i have something soon so if I don't respond that's why

**Comment by Calculatergamer** [comment]
Ok yea that was the problem thank you
