### ISSUE TITLE
Multiple Screens on CEmu

### ISSUE THREAD

**Issue by Orbisculating-Flerovium** [calc84maniac/tiboyce#205]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.3.0
**TI-Boy CE version:** 0.3.0
**Describe your issue:**  
The game works just fine on a physical TI-84 plus CE, but when I use a rom image from [redacted] with CEmu, I get four screens, each flickering and low pixelation. Game appears to play at normal speed, it's just kind of laggy.

What are the steps to reproduce this issue?
-------------------------------------------
1. Download the rom, CEmu
2. Put the files from a game, TI Boy CE, and rom onto CEmu (I also put Clibs if this uses it, though I don't know if that matters)
3. Load a game(I used Legend of Zelda Oracle of Ages)

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
No console logs nor errors, doesn't split when clear is hit for some weird reason, screenshots included. Could be anything from outdated rom to CEmu problems to laggy pc to an actual bug though.
![Screenshot 2024-01-30 at 7 39 54 PM](https://github.com/calc84maniac/tiboyce/assets/126985263/9db888ea-3e55-4de7-938e-f324c7360ee5)  ![Screenshot 2024-01-30 at 7 44 00 PM](https://github.com/calc84maniac/tiboyce/assets/126985263/4a71b0cf-8899-4f4e-a110-a59ad5553f95)

Updates
--------
*The screen colors are also weird
*This only happens for TI Boy CE, not things like Oiram

**Comment by calc84maniac** [comment]
Do you have the LCD SPI option enabled in CEmu? (I assume you're using nightly CEmu because otherwise even TI-Boy's menu probably wouldn't work.)

**Comment by Orbisculating-Flerovium** [comment]
This is probably more of a CEmu question, but how would I see that?

**Comment by calc84maniac** [comment]
It should be in the Settings dock, I'm not at my PC right now so I don't know exactly which tab, but I think it's the first one.

**Comment by Orbisculating-Flerovium** [comment]
Apparently, it was checked, but when I unchecked it things got even worse (even slower, bottom screens look weird) and I can't put it back. Here's an image: 
![Screenshot 2024-02-13 at 9 00 22 PM](https://github.com/calc84maniac/tiboyce/assets/126985263/a6b31737-5bd0-4bcd-b586-7b07a7b8e1fb)
And when I recheck it:
![Screenshot 2024-02-13 at 9 05 47 PM](https://github.com/calc84maniac/tiboyce/assets/126985263/d6ac285e-8f1d-4d23-926e-21e112b5877a)
So I have no clue what's going on

**Comment by calc84maniac** [comment]
Actually now that I think of it, I would like to double-check that you're using the nightly build of CEmu, because there used to be an issue where the SPI setting got corrupted and wasn't enabled by default even when the checkbox was set.

**Comment by Orbisculating-Flerovium** [comment]
v1.3

**Comment by calc84maniac** [comment]
Okay yeah, you'll need the nightly CEmu build to use

**Comment by Orbisculating-Flerovium** [comment]
Thanks
