### ISSUE TITLE
Says no ROM is loaded

### ISSUE THREAD

**Issue by foxboi123** [calc84maniac/tiboyce#207]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:**5.4.0
**TI-Boy CE version:*Alpha 3.0
whenever I try to open a rom with tiboy, it says that no rom is loaded, it might be because of where I'm getting my rom (late games) if someone could tell me where they get their roms and I can try with those I'll know.

What are the steps to reproduce this issue?
-------------------------------------------
1.just attempts to open a game

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
none

**Comment by calc84maniac** [comment]
Does it display any other error before going back to the menu? If not, are you sure you're selecting the ROM and not the Back button?

**Comment by foxboi123** [comment]
I'm sure

**Comment by foxboi123** [comment]
turns out im just stupid XD I was pressing the back button, sorry for wasting your time lol
