### ISSUE TITLE
Is the link cable still being worked on?

### ISSUE THREAD

**Issue by Pippa015** [calc84maniac/tiboyce#208]
Not really a feature request, but I don't really know where to asks this otherwise.

I noticed that it's been over a year since the last update, so I was wondering if it's still being worked on.

**Comment by calc84maniac** [comment]
There's been some work towards it, mainly adding support for loading CE libraries like USBDRVCE.

As for the link support itself, I've been working on a separate test program using USBDRVCE for sending messages back and forth, but I'm getting higher latency than I was expecting and than would be acceptable for Game Boy link play. It could be a configuration issue or something else, but I'll have to get back to it at some point.

As for where to ask, there's an existing issue #30, so I'll be closing this one.

**Comment by ArrowlTCS** [comment]
> As for the link support itself, I've been working on a separate test program using USBDRVCE for sending messages back and forth, but I'm getting higher latency than I was expecting and than would be acceptable for Game Boy link play. It could be a configuration issue or something else, but I'll have to get back to it at some point.

would you mind sharing that program so I could help?

**Comment by calc84maniac** [comment]
I mean sure, it's basically a modification of the toolchain link_library example: https://github.com/CE-Programming/toolchain/tree/master/examples/library_examples/usbdrvce/link_library

I was trying to modify it to send single packets back and forth as fast as possible, but if I recall, I couldn't manage less than 2ms round trip time. Here's a zip of the modified example: [link_library.zip](https://github.com/user-attachments/files/17079954/link_library.zip)

**Comment by ArrowlTCS** [comment]
thank you!
Best,
Neel Jaiswal

*A smile is a valuable tool, my dear. It inspires your friends, keeps your
enemies guessing, and ensures that, no matter what comes your way, YOU'RE
the one in control." ~*Alastor
