### ISSUE TITLE
Crash on "The Machine" after first room

### ISSUE THREAD

**Issue by Ianandstuff** [calc84maniac/tiboyce#212]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … (see in `2nd`+`mem` ->`About`)
**TI-Boy CE version:** … (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
**Describe your issue:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by Eeems** [comment]
It helps when you fill out the issue template instead of just putting a title.

**Comment by calc84maniac** [comment]
I was able to replicate the crash, which is surprisingly a full RAM clear, haven't had to deal with one of those in quite some time. I'll make sure to look into this further.
