### ISSUE TITLE
HELP: Can someone tell me which files to download from the ROM converter?

### ISSUE THREAD

**Issue by FunnyHotDog** [calc84maniac/tiboyce#214]
I don't know which one to download(I have a TI-84 Plus CE that I will have to jailbreak with arTIfiCE) and I don't know which files to download(sorry about this I'm new to both the calculator and TI-Boy). Do I do the bundle or ...?

Options for individual downloads(used tetris as a starter game
Tetri.8xv
TetriR00.8xv
TetriR01.8xv
TetriR02.8xv
TetriR03.8xv
TetriR04.8xv

Also some instructions to put it on there please thanks.

**Comment by Randomnesss-E** [comment]
The bundle should work

**Comment by Randomnesss-E** [comment]
also you can just put the files directly onto the calculator and open the ti-boy app. (if you don't have the apps on there i would use this video for help https://youtu.be/plrj6Pm-6rg?si=JUDmYzCFGywmentN

**Comment by FunnyHotDog** [comment]
Problem: assembly files for cesium and asm hook don't transfer

**Comment by FunnyHotDog** [comment]
ok it started working again thanks so much for your help!
