### ISSUE TITLE
Is there an idea of when the cheat codes update will be released?

### ISSUE THREAD

**Issue by CoolCoderGuy** [calc84maniac/tiboyce#215]
I was just wondering since this hasn't gotten a new release in quite a while.

**Comment by calc84maniac** [comment]
There's no need to create a duplicate issue, one already exists: #146

But for what it's worth, I'd like to get another release out pretty soon before I start on the meat of cheat code support.

**Comment by CoolCoderGuy** [comment]
Oh my bad I didn't see that, thanks for the response
