### ISSUE TITLE
TIBoyDat Missing after a couple of months 

### ISSUE THREAD

**Issue by SomeoneNamedTrent** [calc84maniac/tiboyce#223]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.8.0.0022
**TI-Boy CE version:** Alpha v0.3.0
**Describe your issue:**  I cannot connect to TiBoyCE. Whenever I go to the menu, I get hit with TiBoyDat Missing. I have not put any extra files in this calculator and haven't removed anything. 

What are the steps to reproduce this issue?
-------------------------------------------
1. Apps -> Cabri Junior -> Open -> Artifice
2. Artifice -> TiBoyCe
3. ERROR:  TIBoyDat Missing

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
The only other thing on there is 1:Quit

**Comment by adriweb** [comment]
Well yes you're supposed to transfer all the 8xv files, which TIBoyDat is a part of

**Comment by SomeoneNamedTrent** [comment]
The thing is I have already had TiBoyCE for a year and haven't done anything to it since. Is there something I need to add?

**Comment by adriweb** [comment]
Hmm well who knows what happened. You should probably back up your variables just in case, and transfer all TI Boy files again.

**Comment by SomeoneNamedTrent** [comment]
I think I found the real issue. I backed up all my files and it says i need 10712 more bytes of RAM. Where could I get this?

**Comment by Eeems** [comment]
Delete some variables

**Comment by adriweb** [comment]
Maybe some memory leaked. Press and hold the reset button on the back for around 3-4s, it will clear ram.

**Comment by SomeoneNamedTrent** [comment]
Didn't work. Still only at 86kB and need 11kB more

**Comment by adriweb** [comment]
Well it's not like these files should be in RAM anyway, so make sure you're transferring them to the archive. There should be plenty of space left there (if not... delete some stuff indeed)

**Comment by SomeoneNamedTrent** [comment]
Somethings odd... I dont see anything that can clear up ram. Anything that takes up ram only takes up such a small amount of it (2-20 bytes) and 2 programs that take up 200 bytes.

**Comment by SomeoneNamedTrent** [comment]
I reset all current ram and im back up to 152kb.; Ill test run things and then close if all is well.
