### ISSUE TITLE
Error: Archived

### ISSUE THREAD

**Issue by Subscratchem** [calc84maniac/tiboyce#224]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.0.1.0012
**TI-Boy CE version:** Alpha v0.3.0
**Describe your issue:**  
I first tried running `prgmTIBOYCE` but in the `README.html` file, it said to run `Asm(prgmTIBOYCE)` for my OS ver.
When I run `Asm(prgmTIBOYCE)`, It shows "Error: Archived" with one option: "1: Quit".
Also, there aren't any roms uploaded onto my calculator yet.

What are the steps to reproduce this issue?
-------------------------------------------
1. Run `Asm(prgmTIBOYCE)` on a version 5.0.1.0012 TI-84 Plus CE-T calculator.

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
![Capture 1](https://github.com/user-attachments/assets/a7c69596-528d-4a01-9f2c-c72af8809c0f)

**Comment by Eeems** [comment]
I'm guessing you figured it out, but for someone else finding this, you can't run an archived program without something like cesium.

**Comment by calc84maniac** [comment]
At least, not prior to OS 5.3.0, which is also stated in the readme.
