### ISSUE TITLE
I accidentally added 5.8.2

### ISSUE THREAD

**Issue by Cgross99** [calc84maniac/tiboyce#226]
I accidentally added 5.8.2 update for my calculator. I can't download grade it. 

I try to play games with Cesium but there is no update that works with 5.8.2

Can you please make a version for TI CE 84 (5.8.2)?

**Comment by adriweb** [comment]
Everything works fine in 5.8.2. If Cesium doesn't install, make sure to download its latest version (same with TI-Boy anyway).
Regardless on any version 5.5 or later, you'll need arTIfiCE first.

**Comment by Cgross99** [comment]
You say 5.5 I say 5.8.2 the newest update the they had programmed not 5.5, 5.8.2

**Comment by adriweb** [comment]
Yeah, I'm well aware and as I said, TI-Boy CE and everything else works just fine on 5.8.2. Re-read my message, it is correct.

**Comment by Cgross99** [comment]
And cesium, I get the update from a year ago and it says when I open it not compatible

**Comment by adriweb** [comment]
I literally just tried right now and everything installed and launched TI-Boy just fine on my 5.8.2.
I don't know what you're doing but please follow the steps correctly with the latest version of everything.

**Comment by adriweb** [comment]
For arTIfiCE (which is needed since 5.5.1), follow the steps here to launch the Cesium installer: https://yvantt.github.io/arTIfiCE/
