### ISSUE TITLE
Emulate turning Gameboy off and on

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#24]
Similar to CEmu, with the ability of turning it off and on. The only problem I see is that if you turn it off, it might look like the calc is off, unless a message is displayed. This would help me in doing some game glitches 😉 .

**Comment by LAX18** [comment]
This sounds cool but you have to keep in mind that Ti Boy CE iis already a space issue, adding cool turn on animations could send it over the edge in terms of space. Furthermore, there are new features planned and by doing this, there is less room for those.


My Solution: provide this as an optional appvar, one that, on run, is detected. This way everyone is happy.

**Comment by runer112** [comment]
It sounds like your goal is to be able to turn off the emulated Game Boy to perform glitches like save corruption. Is the "Restart game" option, which turns it off and immediately back on, not sufficient for this purpose? I don't see any real value in turning _and keeping_ the emulated Game Boy off.

**Comment by calc84maniac** [comment]
Agreed, this is covered by the "Restart game" option.
