### ISSUE TITLE
In Pokemon blue every time I catch a pokemon there's an opcode error

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#26]
Just started happening.

**Comment by calc84maniac** [comment]
If you have a save file that's you're consistently triggering this from, I recommend backing it up so you can send it to me. I'm having a lot of trouble replicating these errors myself.

**Comment by jcgter777** [comment]
I just run the game. I'll send all the pokemon blue files when I get home to my own computer.

**Comment by calc84maniac** [comment]
Send only the save files please, the ROM files contain copyrighted data and shouldn't be shared.

**Comment by jcgter777** [comment]
[PKMNBLUE Files.zip](https://github.com/calc84maniac/tiboyce/files/2199040/PKMNBLUE.Files.zip)

There

**Comment by jcgter777** [comment]
What files can I delete to go a little back in the game? It's happened before when I accidentally deleted some files, butI don't know which one(s).

**Comment by jcgter777** [comment]
I pinpointed the actual save file that did the stuff. (probably you already know which one, but here it is:)

[PKMBLSAV.8xv.zip](https://github.com/calc84maniac/tiboyce/files/2217398/PKMBLSAV.8xv.zip)

I think it's because I used the MissingNo glitch one time too many.

**Comment by jcgter777** [comment]
This is also linked to #22 where instead of the opcode error, it RAM resets.

**Comment by runer112** [comment]
This also enters a bad state in bgb, but it doesn't hit an invalid GB opcode. So although both emulators reach a bad state, TI-Boy CE seems to enter an _incorrect_ bad state.

**Comment by jcgter777** [comment]
If this is because of a corrupted save, how can I fix it? If I can't, that's alright because I've almost beat the game again after restarting.

**Comment by runer112** [comment]
@jcgter777 Unless you find some kind of tool designed to fix corrupted Pokemon save files, you might be out of luck.

**Comment by jcgter777** [comment]
Hehe. I'll close this and make a new relevant issue.
