### ISSUE TITLE
I can't get a link for my ROMs

### ISSUE THREAD

**Issue by HappySand6** [calc84maniac/tiboyce#29]
I am new to the whole ROM download deal and I have no clue what I'm doing. I put the file into the website and I told it to convert. It gave me a bunch of prompts but I had no clue how to follow them. What do I do?

**Comment by mateoconlechuga** [comment]
Figure it out, we are not here to help you download illegal roms. It's going to require you to read.

**Comment by HappySand6** [comment]
And this is why I don't deal with tech experts. So dang rude.

**Comment by jcgter777** [comment]
The "whole ROM download deal" is illegal. You're supposed to get your own ROMs from your own Gameboy. If you don't have one, then, too bad. 

And, I'm no tech expert. I just know that this is a fact.

**Comment by adriweb** [comment]
Also, there are some public domain ROMs to download here and there, for instance here https://pdroms.de/files/gameboy/

**Comment by LAX18** [comment]
Okay, I *think* we have misread  @HappySand6 's original question. Assuming you have the .gb file from your GB, you then put it into the website. The website is going to ask you a few prompts, I believe this is what you were having issues with. TBH, it is best to just read the prompts and respond, but please consult this video for more help.
https://m.youtube.com/watch?v=5RUx__X082Y

**Comment by jcgter777** [comment]
*_clap clap_*

**Comment by Legend-of-iPhoenix** [comment]
> Also, there are some public domain ROMs to download here and there, for instance here https://pdroms.de/files/gameboy/

That does not make them any more legal: https://www.nintendo.com/corp/legal.jsp#domain

**Comment by HappySand6** [comment]
OK so I followed the video exactly and nothing happened, rather no files populate as they do in the video. So I guess reading and watching doesn't work for me because I'm just too stupid. Oh well.

**Comment by HappySand6** [comment]
And it's for the game boy advance... sigh. I need to just walk away and come back.

**Comment by jcgter777** [comment]
Read the readme. NO GAMEBOY ADVANCE

**Comment by HappySand6** [comment]
Yep that would me why I need to walk away...

**Comment by calc84maniac** [comment]
> That does not make them any more legal: https://www.nintendo.com/corp/legal.jsp#domain

Not true, Nintendo there is only addressing misconceptions about what is and is not considered public domain. The ROMs hosted on PDRoms are in fact public domain.

Back to the issue at hand, I'm not sure if the online ROM converter actually displays a message to the user if there was a failure. I'm guessing the conversion failed because the ROM file was too large (as GBA games would tend to be).

**Comment by LAX18** [comment]
@HappySand6 Don't walk away, TIBOYCE is TOO GOOD to walk away from :D

**Comment by jcgter777** [comment]
Errrm. Close issue?

**Comment by LAX18** [comment]
I would, @jcgter, it seems as though @HappySand6 is either done with TiBoy CE or has it figured out.

**Comment by calc84maniac** [comment]
Looks like the real issue here falls under #33. Closing.

**Comment by HappySand6** [comment]
I um didn't but that's OK.
