### ISSUE TITLE
There should be an error message on the ROM converter when you input a name over 5 chars

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#31]
It allows you to put more than 5 chars in, but at the end, an "Input" loop happens. A perpetual input prompt. It's always because there was a problem before.

**Comment by adriweb** [comment]
Yeah, for some reason I broke that while fixing some other thing.
I guess I'll fix it soon.

**Comment by calc84maniac** [comment]
This is in the web converter like adriweb mentioned, I assume? I remember putting an error message in the command line version.
