### ISSUE TITLE
Simulate linking between different games/roms as two different gameboys

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#37]
An example is trading pokemon between red and blue all from one calc. One idea is to be able to switch which screen is displayed, or split the screen up.

**Comment by LAX18** [comment]
Neat, But IDK if it is practical.

**Comment by calc84maniac** [comment]
I think at this point, I'd have to say this is very unlikely due to resource and design limitations. A large amount of my design relies on the fact that there will only be one system emulated.
