### ISSUE TITLE
Error:Unsupportedcartridgetype[##]

### ISSUE THREAD

**Issue by TirantRex** [calc84maniac/tiboyce#39]
TI-OS version: 5.3.0.0037
TI-Boy CE version: Alpha v0.1.1

I followed this tutorial on youtube: https://www.youtube.com/watch?v=5RUx__X082Y

I installed 2 games; Metroid II and Kirby's Dream Land 2. Both games gave the error in the title of this post.

(Metroid II: "Error:Unsupportedcartridgetype73" ; KDL2: "Error:Unsupportedcartridgetype3B")

**Comment by calc84maniac** [comment]
It seems like either something is corrupted, or the ROMs were given to the converter in an unexpected format (for example in a RAR archive or something). ZIP archives should work properly, though.

**Comment by calc84maniac** [comment]
Can I get an update on whether you were able to get it to work, or if you're still having problems?

**Comment by TirantRex** [comment]
Apologies. I reinstalled the emulator and reconverted the roms and it worked perfectly! Sorry for not responding.

**Comment by calc84maniac** [comment]
That's good to hear, thanks!
