### ISSUE TITLE
Slowing down randomly 

### ISSUE THREAD

**Issue by jcgter777** [calc84maniac/tiboyce#42]
I've noticed in some games, namely Pokemon Gold and Silver, that the game sometimes slows to ~20% speed. Although good for winning at slots, it's not fun to go walking around like that. It's usually at 60-90% speed. exiting and reopening fixes it, but it's weird. Everytime it happens, I'm doing something different. Is it because the calculator can't process it all that fast?

**Comment by calc84maniac** [comment]
I actually have an idea of what could be causing this, I've encountered it myself before but I kind of let it drift to the back of my mind.

There's this one buffer I use to store information for each block of code that gets recompiled, but I use leftover, unused space in the buffer to store a cache for translating arbitrary jump destinations to recompiled code.

If there are enough code blocks, the block information can run into the cache which causes the cache to be flushed. The situation you're encountering is when there are enough code blocks to almost fill up this buffer, but not enough to force a full JIT flush, which causes this cache to be repeatedly flushed and refilled. This will only happen in games where there are a lot of very small code blocks (which means the main JIT code area doesn't fill up first, which would cause an earlier full flush).

So anyway, this should be fixable by causing some relevant condition to force a full flush before this can become an issue.

**Comment by jcgter777** [comment]
Yeet!
