### ISSUE TITLE
Impossible to make a screenshot of a game.

### ISSUE THREAD

**Issue by valentinbreiz** [calc84maniac/tiboyce#44]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.3.1
**TI-Boy CE version:** 0.1.1
**Describe your issue:**  Transfert error when I try to make a screenshot from TI Connect.

What are the steps to reproduce this issue?
-------------------------------------------
1. Load a game
2. Take a screenshot for TI Connect CE
3. Feel bad

Any logs, error output, screenshot, other comments...?
------------------------------------------------------

![image](https://user-images.githubusercontent.com/18724279/44676880-bf577000-aa34-11e8-8de0-5044844905c0.png)

**Comment by calc84maniac** [comment]
This is not a supported scenario because the OS is not allowed to run any code during emulation, and the screen buffer is not in the format it expects anyway.

It may be possible to build a screenshot feature into the emulator itself, which would perhaps save to a Pic file (I'm a bit surprised nobody made an issue for that yet).

**Comment by valentinbreiz** [comment]
So let's make this x)

**Comment by mateoconlechuga** [comment]
This is silly, literally no program supports capturing a screenshot with the crappy TIConnect. Imho, this issue should be closed.

**Comment by calc84maniac** [comment]
Sure thing. If someone wants to request a screenshot feature for TI-Boy they can make a separate issue for that.

**Comment by LAX18** [comment]
Just use CEmu, that works best.

**Comment by adriweb** [comment]
In this case, transfer your game and state files to CEmu, then you can take your screenshot as you want (even animated screenshot if you need that)

**Comment by valentinbreiz** [comment]
That's what I did thanks!
