### ISSUE TITLE
Impossible to start tiboyce inside TI-SmartView CE

### ISSUE THREAD

**Issue by valentinbreiz** [calc84maniac/tiboyce#45]
What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** 5.2.0.0035
**TI-Boy CE version:** 0.1.1
**Describe your issue:**  When I try to start tiboyce the emulator just freeze.

What are the steps to reproduce this issue?
-------------------------------------------
1. Install it like on a normal calculator.
2. Start the prgm with Asm()
3. Cry.

Any logs, error output, screenshot, other comments...?

![image](https://user-images.githubusercontent.com/18724279/44681682-94274d80-aa41-11e8-98a2-78f064b2eaeb.png)

Frozen here.

**Comment by calc84maniac** [comment]
This is an issue with TI-SmartView CE, which does not attempt to emulate the TI-84+CE hardware accurately.

I recommend using [CEmu](https://github.com/CE-Programming/CEmu) if you want to emulate TI-Boy CE.

**Comment by valentinbreiz** [comment]
Thanks it works ! I can make my screenshot now lol
