### ISSUE TITLE
NEVER use Hacked ROMS (Rom Hacking)

### ISSUE THREAD

**Issue by KellyDi0te** [calc84maniac/tiboyce#47]
Hello, it's just for saying for everybody here, that you should never use Hacked Roms, from Romhacking.net or other websites like this, because it will destroy your calculator.
When you run the hacked rom, the calculator will instantly screen freez, like a blue screen on windows, and the only way to save the calculator is reset it.

Be careful.

**Comment by calc84maniac** [comment]
Could you please provide an example of a hacked ROM that does this? I'd like to fix the issue, but it's really not something that'll happen for every hacked ROM.

By the way, a freeze on its own isn't going to destroy your calculator (unless you throw it in a garbage compactor out of frustration), though you'll probably lose any data that's not saved in Archive memory. This risk is stated clearly at the top of the readme, and part of why the emulator is still an Alpha version.

**Comment by KellyDi0te** [comment]
https://www.romhacking.net/hacks/3784/ This one made this for example

**Comment by calc84maniac** [comment]
It appears that this hack isn't properly detecting TI-Boy as running a non-color Game Boy model, so it's attempting to display Game Boy Color graphics. This looks really weird, but it doesn't seem to be freezing. Is there anything specific you do with the game that causes the emulator to freeze? Are you not able to open the emulator menu with the `clear` button or exit with `on`?

It might also be good to make sure you applied the patch correctly by making sure the ROM runs properly in an accurate emulator like BGB, if you haven't already.

**Comment by KellyDi0te** [comment]
I have just opened TiBoy, choose the game and my calculator instantly froze, I can't do anything, just reset...

**Comment by calc84maniac** [comment]
On my end at least, I've fixed emulation of the Super Mario Land 2 DX ROM hack so it detects TI-Boy as an original Game Boy. If there are more issues with hacked ROMs, open a new issue for the particular problem.

**Comment by MaverickHunter07** [comment]
What about translations? They're on the same website, but on a different section.
