### ISSUE TITLE
Make stack emulation more robust

### ISSUE THREAD

**Issue by calc84maniac** [calc84maniac/tiboyce#56]
I was a bit lazy in my initial implementation of stack emulation in favor of simplicity and speed (by using a direct pointer as the stack pointer). In addition to potentially leading to inaccuracies, a buggy game could possibly corrupt RAM or crash the emulator.

I don't want to fully abandon the speed benefits of using a direct pointer, but I need to add logic to detect when the stack pointer moves between regions of Game Boy address space. Additionally, adding logic to properly handle writes to special areas like the ROM, VRAM, and memory-mapped ports would improve accuracy even more.

**Comment by sorenbug** [comment]
Does this have anything to do with #101?
