### ISSUE TITLE
Runtime error encountered at random during emulation

### ISSUE THREAD

**Issue by calc84maniac** [calc84maniac/tiboyce#6]
This issue seems to have been observed most in Pokémon Red, but may very well apply to other games.

Due to the randomness of triggering the bug, it seems to be some kind of JIT issue.

May want to add some kind of core dump feature to help analyze the bug when it occurs.

**Comment by runer112** [comment]
I concur about the core dump feature.

**Comment by calc84maniac** [comment]
Fixed by https://github.com/calc84maniac/tiboyce/commit/72e66a2d319d4ccbfa573c0095a96501e8000b8e.
