### ISSUE TITLE
Controls Not Working in Faceball 2000

### ISSUE THREAD

**Issue by MangoFett** [calc84maniac/tiboyce#63]
I am playing the game "Faceball 2000" and while I am able to get past the title screen and into a game I can't move. I am using the proper controls, so I am not sure why it won't work. Thanks.

**Comment by calc84maniac** [comment]
Looks like something's definitely not being emulated properly with this game. The timer runs down really slowly as well, despite the game emulating at full speed. I'll see what I can figure out.

**Comment by MangoFett** [comment]
So you think it’s the games fault or the emulator?

**Comment by calc84maniac** [comment]
It's a problem with the emulator, which is being triggered by something that the game does. Just need to figure out what's causing the problem, because it's not immediately obvious.

**Comment by MangoFett** [comment]
Ok thanks. Let me know what happens.

**Comment by jcgter777** [comment]
NDS emulators (and newer consoles in general) get their time from the computer's clock (or whatever it's running on). But, what does it count time by, if you put it on turbo the whole way (like shown in-game saving)?

**Comment by MangoFett** [comment]
So you want me to put it on turbo and then what?

**Comment by MangoFett** [comment]
Ok cool.

**Comment by ndye** [comment]
@MangoFett is your TI-Calc's system time set to the same time that is set in the Emulator Options tab in the emulator? Meaning if your TI system time is set to EST then Time zone in Emulation options is set to UTC-5:00 without DST enabled.

**Comment by ndye** [comment]
Won't fix your particular problem but will help prevent any future problems.

**Comment by ndye** [comment]
A fair thing to make note of is that the game obviously makes use of very obscure parts of the Gameboy code because even on mGBA on my mac mini it runs incredibly slow. It clearly uses an unknown part of the GB code to run at reasonable rates on the original console.

**Comment by MangoFett** [comment]
Yeah there’s not a lot of 3D gameboy games lol. I’m surprised it doesn’t
work at all though.

**Comment by MaverickHunter07** [comment]
I was wondering how to post this but I found out someone already did by the time I found this bug report.

**Comment by MaverickHunter07** [comment]
I was wondering how to post this but I found out someone already did by the time I found this bug report.

**Comment by MaverickHunter07** [comment]
Oh yeah! I found a solution to this problem. I don't know why this works but it just does. Stand still, and keep restarting the game until it works. There's a reset option when you press clear. If you exit the emulator for a bit, though, you will have to restart again.

**Comment by MangoFett** [comment]
That’s not a very good solution though lol.

**Comment by MaverickHunter07** [comment]
It still works though!

**Comment by MangoFett** [comment]
No it doesn’t. I restarted it like 20 times.

**Comment by MaverickHunter07** [comment]
Whoops. Sorry to mention that it works only on the second release of ti-boy ce. If that doesn't work after many tries, try the first release.

**Comment by MangoFett** [comment]
What if it’s a problem with the ROM file? It seems like that could be it.
