### ISSUE TITLE
New warning upon building

### ISSUE THREAD

**Issue by ndye** [calc84maniac/tiboyce#64]
Upon building on the latest commit the following warning is issued:
```
exporter: warning SW551: The output file is larger than 24KB
```
I just wanted to clarify that this is intended and will not affect the performance of the app.

**Comment by adriweb** [comment]
Yes, and it's actually normal if you don't have the very latest version of spasm-ng. It got fixed precisely yesterday as this warning didn't apply for the eZ80 models: https://github.com/alberthdev/spasm-ng/commit/e6e9a42ab95bd25d8cf92607f270e7a34efd8edf
You'll need to build it yourself to get this change, however, as a release isn't yet available.

**Comment by calc84maniac** [comment]
I'll probably add a mention of this to the readme the next time I update it.
