### ISSUE TITLE
ROM format incompatible with OS 5.3.5+

### ISSUE THREAD

**Issue by critor** [calc84maniac/tiboyce#70]
Hi.

OS 5.3.5.0024 released for the TI-83 Premium CE is supporting a new Python appvar type.
I suppose it implies a bigger header.

Converted appvars sent to the calculator before the update are still present and working.

But you can't completely send new converted appvars.

TI-Connect CE 5.3.5 reports some appvar are too big, the ones closest to the old ~64K limit.
I suppose there is now a new lower ~64K limit.

Using the older TI-Connect CE 5.3.0 doesn't change this, so I suppose it's the OS which is rejecting the appvars.

Thanks, and sorry to give you so much work...

**Comment by calc84maniac** [comment]
I updated the ROM converter to respect the new limit. In the meantime until the next release, the web converter will reflect this change.

**Comment by adriweb** [comment]
(Web converter updated too)
