### ISSUE TITLE
Joust-Defender Rom Freezes when spawning enemies in Joust (Defender works)

### ISSUE THREAD

**Issue by programmer2514** [calc84maniac/tiboyce#73]
TI-OS version: 5.3.1.0058
TI-Boy CE version: v0.1.2a

Every time I run the Joust-Defender ROM, Defender works perfectly, but Joust freezes the ROM.
It does NOT freeze the emulator, but it makes Joust unplayable.
I don't know what I'm doing wrong. Perhaps the ROM was converted wrong?

1. Convert the Joust-Defender GB ROM
2. Send it to the calc as separate AppVars
3. Run the game
4. Select Joust
5. Press A
6. The ROM freezes

**Comment by ndye** [comment]
Are you sure that this was not a preexisting problem with the Physical Game? Also try different versions of the ROM and see if that helps.
