### ISSUE TITLE
Error: Syntax

### ISSUE THREAD

**Issue by TheShadowYTG** [calc84maniac/tiboyce#74]
---------------------------------------------
TI-OS version: 5.2.2.0043
TI-Boy CE version: TI-84 Plus CE
What are the steps to reproduce this issue?
-------------------------------------------
1. Put everything in my calculator in calculator explorer
2. Hit "prgm"
3. Hit TIBOYCE
4. Clicked enter again

It shows me a screen saying "Check all arguments entered."

Help?

**Comment by calc84maniac** [comment]
As it says in the readme, prior to OS 5.3 you need to run it with `Asm(prgmTIBOYCE)`.
