### ISSUE TITLE
V-Rally - Championship Edition title screen missing cursor

### ISSUE THREAD

**Issue by MaverickHunter07** [calc84maniac/tiboyce#78]
TI-OS version: 5.3.1.0058
TI-Boy CE version: v0.1.2

V-Rally - Championship Edition's title screen does not show the pointer when selecting the game mode.

Convert V-Rally - Championship Edition GB ROM
Send it to the calc as separate AppVars
Run the game
Select VRaCE
Press A
No cursor visible.

**Comment by calc84maniac** [comment]
This glitch seems to be due to the renderer not supporting mid-frame sprite palette changes. I'll have to look more seriously into the possibility of supporting that, even if it might be a bit slow.
