### ISSUE TITLE
Enemies do not show up in F-15 Strike Force Eagle 

### ISSUE THREAD

**Issue by LAX18** [calc84maniac/tiboyce#8]
As I was playing this game, and went to fly, I noticed that enemy aircraft do not show up. Neither do bullets when I shoot. I have already tried disabling frameskip to see if it was skipping over the frames where they are visible, but that did not work. I know that the planes and bulllets show because I have seen gameplay from other people.

**Comment by LAX18** [comment]
So here is a video of my gameplay compared to youtube.
Youtube:
https://m.youtube.com/watch?v=67ZqaNEKsTc

**Comment by calc84maniac** [comment]
I wasn't expecting games to run sprite DMA in the middle of a frame, since supposedly the sprite memory area isn't accessible long enough for a full copy. Supposedly. This game has other ideas, so I guess I can oblige it.

**Comment by LAX18** [comment]
Thank you for taking the time to fix this. Can I build the latest code now? Do you consiter it stable enough?

**Comment by adriweb** [comment]
Well the same level of "risk" applies, it's still the alpha + a few bugfies, so heh...
Build instructions are in the readme

**Comment by LAX18** [comment]
Just built and appears to work great! Once more, thanks!

**Comment by calc84maniac** [comment]
Reopening this issue because the fix broke sprite display in Mega Man: Dr. Wily's Revenge.

**Comment by calc84maniac** [comment]
No problem, it was my mistake that broke the other things anyway, heh.
