### ISSUE TITLE
Dragon Ball Z- Goku Gekitouden Krillin blows apart

### ISSUE THREAD

**Issue by MaverickHunter07** [calc84maniac/tiboyce#82]
TI-OS version: 5.3.1.0058
TI-Boy CE version: v0.1.2

As soon as Krillin reaches his first point of dialogue, his sprite appears to blow up, taking some of the background with it.

Dragon Ball Z- Goku Gekitouden GB ROM
Send it to the calc as separate AppVars
Run the game
Select DBZGG
Press A
Start the game
Play until Krillin speaks
The screen acts weird

**Comment by calc84maniac** [comment]
Couldn't reproduce this in v0.1.2 or v0.2.0, feel free to reopen the issue if it still exists in v0.2.0.
