### ISSUE TITLE
Rom Converter Doesn't Allow Grand Theft Auto

### ISSUE THREAD

**Issue by ghost** [calc84maniac/tiboyce#84]
I put in a grand theft auto rom which is a dual system game but the rom converter doesn't even try.

**Comment by ndye** [comment]
Are you using the online converter or the compiled one?

**Comment by SuperDaveMan** [comment]
It is a black cartridge game therefor it should work on both systems, also I am using the online converter.

**Comment by calc84maniac** [comment]
Fixed by #138. However, the ROM is too large to fit in Archive memory. Will have to wait and see if a compression option will be possible in the future.
