### ISSUE TITLE
Crash with new CE hardware (83PCE Python, and probably 84+CE rev M)

### ISSUE THREAD

**Issue by verziok** [calc84maniac/tiboyce#85]
So sorry for spellings mistakes i'm french, so I have a new calculator, TI-83 prenium CE Python edition, when i want to launch a game in TIBoyCE, there is a white or a blue screen and I can't do anything except reset the calculator, so after the reset, i loose a lot of ram and when i re-launch a game, that do the same thing until that my ram is low and they need more ram

do you have a solution ?

**Comment by commandblockguy** [comment]
The Python Edition calculators have slightly different hardware than the original CEs, so some programs, likely including TI-Boy CE, are not compatible with them. The Python Edition calculators are still new, so it's just a matter of time before programs get fixed.

As for losing memory over time, this is a known phenomenon on the EP. It happens every time the reset button is pressed. You can get the memory "back" by pressing 2nde+mém, then selecting 7: Réinitialiser and then 1: Toute la RAM.

**Comment by adriweb** [comment]
Faster way to reset the RAM: hold the "Reset" button on the back for like 2-3s. Then press the [on] button.

**Comment by adriweb** [comment]
84+CE rev M confirmed, see #87.

**Comment by calc84maniac** [comment]
I've made a new release (https://github.com/calc84maniac/tiboyce/releases/tag/v0.1.3) which should fix this crash. Please try it and let me know if it works so I can close this issue.

**Comment by verziok** [comment]
Yes that's work now on the TI-83 PCE python ! good job and thank you for your quick reply !
