### ISSUE TITLE
White screen when loading a rom

### ISSUE THREAD

**Issue by SGSean** [calc84maniac/tiboyce#87]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?
---------------------------------------------
**TI-OS version:** … (5.3.6)
**cant load my roms, whenever i do its just a white screen and a have to reset the calculator:**  
… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by adriweb** [comment]
Which calculator is it exactly?
And what's the date code at the back of the calc? It's located at the right of the serial number and it looks like L-1234M.
This could lead to pinpointing which révisions have the issues.

**Comment by SGSean** [comment]
its the TI 84 plus CE, L-0519M is the code

**Comment by adriweb** [comment]
Alright, that's the new hardware version that was supposedly the same as the new 83 (which has a github issue already here) but we hadn't seen any proof of it yet.
Congrats on being the first we see with the new hardware revision. And hopefully the issue can be fixed when the HW is understood better.

**Comment by SGSean** [comment]
Ah ok, thanks for the help.

**Comment by adriweb** [comment]
Dup of #85. Let's close this one and you can subscribe to the original to get notifications.

**Comment by adriweb** [comment]
@SGSean hey, could you check what your boot version is?
At the home screen, press [mode] then [alpha] then [ln].
There will be a screen with versions, you can type those here or screenshot it, as you want. 
Then press clear to exit. 
Thanks!

**Comment by ender994** [comment]
I've also had this problem as well, just wondering if there is any way to fix it. Thanks btw!

**Comment by calc84maniac** [comment]
I'm getting a new-model calculator shipped in so I can see about developing a quick fix. Will probably be after a couple weeks, hopefully not longer than a month.

**Comment by rollo8** [comment]
I just had this issue with pokemon blue and tetris on mine too yeah
