### ISSUE TITLE
What are the bundles created by the ROM converted?

### ISSUE THREAD

**Issue by badbob001** [calc84maniac/tiboyce#90]
The ROM Converter has options to download:
- TI-84 Plus CE bundle
- TI-83 Premium CE bundle
- all files in a .zip

I can't find any explanation on the purpose of the bundles, which only contain a single file. So if I have a TI-84+CE, do I just need to load the corresponding bundle file (along with emu files)? With the CEmu emulator and a TI-84+CE 5.3 rom, loading the smaller individual *.8xv files work, but when I load the single .b84 file, I get this error:
**ERROR: TIBoyDat Missing**

So I'm hesitant to try the same on my real TI-84+CE.

**Comment by adriweb** [comment]
The bundle is a single file that's actually an archive (and basically a zip file). It contains the ROM segments from the converted ROM.
You can transfer it with TI-Connect CE.

TIBoyDat and the rest are from the main TI-Boy CE download: https://github.com/calc84maniac/tiboyce/releases/latest
