### ISSUE TITLE
Legend of Zelda is showing up as corrupted file, can't transfer.

### ISSUE THREAD

**Issue by HamzaChaudhry123** [calc84maniac/tiboyce#91]
(Thanks for reporting an issue! Please make sure to fill out the blanks below.)

What's wrong, and with what software version?

When I try to transfer Legend of Zelda: Links Awakening, it gives me an error saying the file is corrupt.
---------------------------------------------
**TI-OS version:** 5.4.0034 (see in `2nd`+`mem` ->`About`)
**TI-Boy CE version:** 0.1.3 (shown on the TI-Boy menu, or if you built it yourself please specify which commit)
**Describe your issue:** When I try to transfer Legend of Zelda: Links Awakening, it gives me an error saying the file is corrupt.

… (including, if applicable what you expect vs. what happens)  

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
…

**Comment by badbob001** [comment]
I have the same issue. TI Connect CE tells me that the *.b84 file is corrupt. If I exact the contents and transfer just the *.8xv files, there is no issue.

**Comment by adriweb** [comment]
Does that only happen with this game?

**Comment by BopItFreak** [comment]
I got that rom to work. Are you using the game boy color version? The original gameboy version is a bit harder to find.

**Comment by JacobKotrla** [comment]
I was able to use the website to convert and run the US 3DS Virtual Console LADX ROM (MD5: 7351DAA3C0A91D8F6FE2FBCCA6182478).

**Comment by ndye** [comment]
FYI @adriweb I have never been able to use the *.b84 output on the online converter but it works fine on the local version.

**Comment by calc84maniac** [comment]
Likely fixed by #137
