### ISSUE TITLE
Add an "Are you sure?" option when loading save states!!!!!!!

### ISSUE THREAD

**Issue by SilentGamer475** [calc84maniac/tiboyce#92]
I literally was just playing Pokemon Red on my calculator when I accidentally hit the "load save state" key. I some had set a save state when I only have 2 hours on the game, and I accidentally hit it just after hitting 7 hours. I lost 4 real-life hours of work that was spanned over the course of a week in 1 second. I was so close to getting a gyrados (I had been grinding for 2 hours straight) and I lost it all.

The solution I really want and really wish I could get back all my wasted time for is to simply add an "are you sure" textbox that appears whenever you press the key. This would have saved me from tears and anger from losing all that time in a fraction of a second. I truly am pissed and think this should get fixed so it doesn't affect other players.

**Comment by JacobKotrla** [comment]
I wish there was a toggle deep in settings that enabled or disabled save states entirely (maybe a separate toggle for the autosavestate). This could keep savestates convenient for those who want to use them, while also preventing those who do not wish to use savestates from accidentally using them.

**Comment by adriweb** [comment]
I think that's a valid feature request, let's not close it. We'll see what @calc84maniac says.

**Comment by SilentGamer475** [comment]
I’m sorry if I sound rude in this suggestion, it was nearing midnight after a long day and I really just wanted to let off some steam. I’m feeling better today and I’ve recently been working on getting back up to where I was. Also, sorry for the unnecessary exclamation points.
