### ISSUE TITLE
Question: Why did you use asm and not C lib

### ISSUE THREAD

**Issue by BopItFreak** [calc84maniac/tiboyce#93]
Why didn't you use the C libraries for ti84plusCE, and instead used assembly?

**Comment by Eeems** [comment]
Probably because he started before the C libraries were a thing.

**Comment by adriweb** [comment]
Even then - most of the code is so low-level (close to the hardware, down to register optimizations everywhere, stack manipulation and "hacks", self modifying code, etc) that it would simply not have been possible to do the same in C, let alone with the same performance (and by the way, ZDS isn't great at optimizing code anyway, so might as well write optimized assembly by hand)
