### ISSUE TITLE
Emulator won't start

### ISSUE THREAD

**Issue by BurrTruman** [calc84maniac/tiboyce#96]
**TI-OS version:** 5.1.5.0019
**TI-Boy CE version:** … Alpha 0.1.3
**Describe your issue:**  
Whenever I run 'prgm' and select TIBOY, it does not display a list. If I press enter, it just displays an error.

What are the steps to reproduce this issue?
-------------------------------------------
1. Click prgm.
2. Select TIBOY.
3. Watch as the readout "prgmTIBOYCE" shows up.
4. Cry silently.

![Capture1-1569535792329](https://user-images.githubusercontent.com/55858559/65728418-767f4a00-e080-11e9-8177-00e76985e980.png)
![Capture2-1569535814770](https://user-images.githubusercontent.com/55858559/65728421-826b0c00-e080-11e9-863b-1f9636972577.png)
![Capture3-1569535822972](https://user-images.githubusercontent.com/55858559/65728425-872fc000-e080-11e9-9958-1f70da196386.png)

**Comment by Eeems** [comment]
This is not a bug. The error message gives you full information on what to do to resolve the error. TI-OS does not allow for running of programs from the Archive. They must be unarchived and in RAM before you can run them. The only way to run programs in archive is to use a shell that will copy the program into RAM before executing them.

**Comment by BurrTruman** [comment]
Unarchived, it now gives a syntax error.

**Comment by calc84maniac** [comment]
The readme states that if you are running an OS earlier than 5.3, the launcher must be unarchived and executed using the `Asm()` command from the Catalog. You'll need to either update your operating system or run it in this specific way.

**Comment by BurrTruman** [comment]
That worked, much thanks!
